// <auto-generated />
using System;
using Edulytics.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Edulytics.Data.Migrations
{
    [DbContext(typeof(EdulyticsDbContext))]
    [Migration("20260816174615_Phase13PostgreSqlBaseline")]
    partial class Phase13PostgreSqlBaseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Edulytics.Core.Entities.AcademicYear", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("EndsOn")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId", "Name")
                        .IsUnique();

                    b.ToTable("AcademicYears", (string)null);
                });

            modelBuilder.Entity("Edulytics.Core.Entities.Assessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcademicYearId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("AssessmentDate")
                        .HasColumnType("date");

                    b.Property<Guid>("ClassGroupId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("MaxScore")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TermId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("SchoolId", "SubjectId");

                    b.HasIndex("SchoolId", "AcademicYearId", "ClassGroupId");

                    b.HasIndex("SchoolId", "AcademicYearId", "TermId");

                    b.HasIndex("SchoolId", "ClassGroupId", "TermId", "Title")
                        .IsUnique();

                    b.ToTable("Assessments", (string)null);
                });

            modelBuilder.Entity("Edulytics.Core.Entities.AssessmentQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("MaxScore")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId", "AssessmentId", "Order")
                        .IsUnique();

                    b.ToTable("AssessmentQuestions", (string)null);
                });

            modelBuilder.Entity("Edulytics.Core.Entities.AssessmentResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EnteredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EnteredByUserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Percentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Score")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EnteredByUserId");

                    b.HasIndex("SchoolId", "StudentProfileId");

                    b.HasIndex("SchoolId", "AssessmentId", "StudentProfileId")
                        .IsUnique();

                    b.ToTable("AssessmentResults", (string)null);
                });

            modelBuilder.Entity("Edulytics.Core.Entities.ClassAssessmentTrend", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcademicYearId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("AssessmentDate")
                        .HasColumnType("date");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("AssessmentTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("AtRiskStudentCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("AveragePercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime>("CalculatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ClassGroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<int>("StudentCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId", "AssessmentId")
                        .IsUnique();

                    b.HasIndex("SchoolId", "SubjectId");

                    b.HasIndex("SchoolId", "AcademicYearId", "ClassGroupId", "SubjectId", "AssessmentDate");

                    b.ToTable("ClassAssessmentTrends", (string)null);
                });

            modelBuilder.Entity("Edulytics.Core.Entities.ClassGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcademicYearId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("GradeLevelId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NormalizedCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasAlternateKey("SchoolId", "Id");

                    b.HasIndex("SchoolId", "GradeLevelId");

                    b.HasIndex("SchoolId", "AcademicYearId", "NormalizedCode")
                        .IsUnique();

                    b.ToTable("ClassGroups", (string)null);
                });

            modelBuilder.Entity("Edulytics.Core.Entities.ClassOutcomeSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcademicYearId")
                        .HasColumnType("uuid");

                    b.Property<int>("AtRiskStudentCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("AverageMasteryPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime>("CalculatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ClassGroupId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("EarnedScore")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<int>("EvidenceCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("LearningOutcomeId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PossibleScore")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<int>("StudentCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId", "LearningOutcomeId");

                    b.HasIndex("SchoolId", "SubjectId");

                    b.HasIndex("SchoolId", "AcademicYearId", "ClassGroupId", "SubjectId", "LearningOutcomeId")
                        .IsUnique();

                    b.ToTable("ClassOutcomeSummaries", (string)null);
                });

            modelBuilder.Entity("Edulytics.Core.Entities.ClassTopicSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcademicYearId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CalculatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ClassGroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CurriculumTopicId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("MasteryPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("OutcomeCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<int>("StudentCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("WeakOutcomeCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId", "CurriculumTopicId");

                    b.HasIndex("SchoolId", "SubjectId");

                    b.HasIndex("SchoolId", "AcademicYearId", "ClassGroupId", "SubjectId", "CurriculumTopicId")
                        .IsUnique();

                    b.ToTable("ClassTopicSummaries", (string)null);
                });

            modelBuilder.Entity("Edulytics.Core.Entities.CurriculumFramework", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("OwnerSchoolId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProviderName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerSchoolId", "NormalizedCode")
                        .IsUnique();

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("OwnerSchoolId", "NormalizedCode"), false);

                    b.ToTable("CurriculumFrameworks", (string)null);
                });

            modelBuilder.Entity("Edulytics.Core.Entities.CurriculumFrameworkVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<Guid>("FrameworkId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedVersionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VersionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("FrameworkId", "NormalizedVersionCode")
                        .IsUnique();

                    b.ToTable("CurriculumFrameworkVersions", (string)null);
                });

            modelBuilder.Entity("Edulytics.Core.Entities.CurriculumTopic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FrameworkVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GradeLevelId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FrameworkVersionId");

                    b.HasIndex("SchoolId", "GradeLevelId");

                    b.HasIndex("SchoolId", "SubjectId");

                    b.HasIndex("SchoolId", "FrameworkVersionId", "SubjectId", "GradeLevelId", "Name")
                        .IsUnique();

                    b.HasIndex("SchoolId", "FrameworkVersionId", "SubjectId", "GradeLevelId", "Order")
                        .IsUnique()
                        .HasDatabaseName("IX_CurriculumTopics_SchoolId_FrameworkVersionId_SubjectId_Gra~1");

                    b.ToTable("CurriculumTopics", (string)null);
                });

            modelBuilder.Entity("Edulytics.Core.Entities.GradeLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId", "Name")
                        .IsUnique();

                    b.HasIndex("SchoolId", "Order")
                        .IsUnique();

                    b.ToTable("GradeLevels", (string)null);
                });

            modelBuilder.Entity("Edulytics.Core.Entities.ImportBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CompletedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("integer");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("ImportType")
                        .HasColumnType("integer");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<int>("RowCount")
                        .HasColumnType("integer");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("RowsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("ValidRowCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompletedByUserId");

                    b.HasIndex("UploadedByUserId");

                    b.HasIndex("SchoolId", "CreatedAtUtc");

                    b.HasIndex("SchoolId", "UploadedByUserId", "ImportType", "FileHash")
                        .IsUnique();

                    b.ToTable("ImportBatches", (string)null);
                });

            modelBuilder.Entity("Edulytics.Core.Entities.ImportValidationError", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ColumnName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ImportBatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("RawValue")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("RowNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId", "ImportBatchId", "RowNumber");

                    b.ToTable("ImportValidationErrors", (string)null);
                });

            modelBuilder.Entity("Edulytics.Core.Entities.LearningOutcome", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("FrameworkVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GradeLevelId")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Weight")
                        .HasPrecision(6, 3)
                        .HasColumnType("numeric(6,3)");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId", "TopicId", "Order")
                        .IsUnique();

                    b.HasIndex("SchoolId", "FrameworkVersionId", "SubjectId", "GradeLevelId", "Code")
                        .IsUnique();

                    b.HasIndex("SchoolId", "FrameworkVersionId", "SubjectId", "GradeLevelId", "TopicId")
                        .HasDatabaseName("IX_LearningOutcomes_SchoolId_FrameworkVersionId_SubjectId_Gra~1");

                    b.ToTable("LearningOutcomes", (string)null);
                });

            modelBuilder.Entity("Edulytics.Core.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AvailableAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProcessingAttempts")
                        .HasColumnType("integer");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid?>("SchoolId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .IsUnique();

                    b.HasIndex("SchoolId", "ProcessedAtUtc");

                    b.HasIndex("ProcessedAtUtc", "AvailableAtUtc", "OccurredAtUtc");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("Edulytics.Core.Entities.QuestionLearningOutcome", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssessmentQuestionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LearningOutcomeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId", "LearningOutcomeId");

                    b.HasIndex("SchoolId", "AssessmentQuestionId", "LearningOutcomeId")
                        .IsUnique();

                    b.ToTable("QuestionLearningOutcomes", (string)null);
                });

            modelBuilder.Entity("Edulytics.Core.Entities.School", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ArchivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultCulture")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedSchoolCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("SchoolCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedSchoolCode")
                        .IsUnique();

                    b.ToTable("Schools", (string)null);
                });

            modelBuilder.Entity("Edulytics.Core.Entities.SchoolAnalyticsSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcademicYearId")
                        .HasColumnType("uuid");

                    b.Property<int>("AtRiskStudents")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CalculatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CriticalOutcomeCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LatestSourceUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("OverallMasteryPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<int>("StudentsWithEvidence")
                        .HasColumnType("integer");

                    b.Property<int>("WeakTopicCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId", "AcademicYearId")
                        .IsUnique();

                    b.ToTable("SchoolAnalyticsSnapshots", (string)null);
                });

            modelBuilder.Entity("Edulytics.Core.Entities.SchoolCurriculumAdoption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AcademicYearId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FrameworkVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GradeLevelId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FrameworkVersionId");

                    b.HasIndex("SchoolId", "GradeLevelId");

                    b.HasIndex("SchoolId", "SubjectId");

                    b.HasIndex("SchoolId", "AcademicYearId", "GradeLevelId", "SubjectId")
                        .IsUnique()
                        .HasFilter("\"IsPrimary\" = TRUE");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("SchoolId", "AcademicYearId", "GradeLevelId", "SubjectId"), false);

                    b.HasIndex("SchoolId", "AcademicYearId", "GradeLevelId", "SubjectId", "FrameworkVersionId")
                        .IsUnique()
                        .HasDatabaseName("IX_SchoolCurriculumAdoptions_SchoolId_AcademicYearId_GradeLev~1");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("SchoolId", "AcademicYearId", "GradeLevelId", "SubjectId", "FrameworkVersionId"), false);

                    b.ToTable("SchoolCurriculumAdoptions", (string)null);
                });

            modelBuilder.Entity("Edulytics.Core.Entities.StudentAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssessmentQuestionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssessmentResultId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Score")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId", "AssessmentQuestionId");

                    b.HasIndex("SchoolId", "AssessmentResultId", "AssessmentQuestionId")
                        .IsUnique();

                    b.ToTable("StudentAnswers", (string)null);
                });

            modelBuilder.Entity("Edulytics.Core.Entities.StudentEnrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcademicYearId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassGroupId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EnrolledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId", "StudentProfileId");

                    b.HasIndex("SchoolId", "AcademicYearId", "ClassGroupId");

                    b.HasIndex("SchoolId", "AcademicYearId", "StudentProfileId")
                        .IsUnique();

                    b.ToTable("StudentEnrollments", (string)null);
                });

            modelBuilder.Entity("Edulytics.Core.Entities.StudentOutcomeMastery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcademicYearId")
                        .HasColumnType("uuid");

                    b.Property<int>("Band")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CalculatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ClassGroupId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("EarnedScore")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<int>("EvidenceCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("LearningOutcomeId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("MasteryPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("PossibleScore")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId", "LearningOutcomeId");

                    b.HasIndex("SchoolId", "StudentProfileId");

                    b.HasIndex("SchoolId", "SubjectId");

                    b.HasIndex("SchoolId", "AcademicYearId", "ClassGroupId", "SubjectId", "StudentProfileId", "LearningOutcomeId")
                        .IsUnique();

                    b.ToTable("StudentOutcomeMasteries", (string)null);
                });

            modelBuilder.Entity("Edulytics.Core.Entities.StudentProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(205)
                        .HasColumnType("character varying(205)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NormalizedStudentNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("\"UserId\" IS NOT NULL");

                    b.HasIndex("SchoolId", "NormalizedStudentNumber")
                        .IsUnique();

                    b.ToTable("StudentProfiles", (string)null);
                });

            modelBuilder.Entity("Edulytics.Core.Entities.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NormalizedCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId", "NormalizedCode")
                        .IsUnique();

                    b.ToTable("Subjects", (string)null);
                });

            modelBuilder.Entity("Edulytics.Core.Entities.TeacherAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcademicYearId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassGroupId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeacherUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeacherUserId");

                    b.HasIndex("SchoolId", "SubjectId");

                    b.HasIndex("SchoolId", "AcademicYearId", "ClassGroupId");

                    b.HasIndex("SchoolId", "TeacherUserId", "ClassGroupId", "SubjectId")
                        .IsUnique();

                    b.ToTable("TeacherAssignments", (string)null);
                });

            modelBuilder.Entity("Edulytics.Core.Entities.Term", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcademicYearId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("EndsOn")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId", "AcademicYearId", "Name")
                        .IsUnique();

                    b.ToTable("Terms", (string)null);
                });

            modelBuilder.Entity("Edulytics.Data.Identity.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Edulytics.Data.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex")
                        .HasFilter("\"NormalizedEmail\" IS NOT NULL");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("SchoolId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Edulytics.Core.Entities.AcademicYear", b =>
                {
                    b.HasOne("Edulytics.Core.Entities.School", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Edulytics.Core.Entities.Assessment", b =>
                {
                    b.HasOne("Edulytics.Data.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edulytics.Core.Entities.School", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edulytics.Core.Entities.AcademicYear", null)
                        .WithMany()
                        .HasForeignKey("SchoolId", "AcademicYearId")
                        .HasPrincipalKey("SchoolId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edulytics.Core.Entities.Subject", null)
                        .WithMany()
                        .HasForeignKey("SchoolId", "SubjectId")
                        .HasPrincipalKey("SchoolId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edulytics.Core.Entities.ClassGroup", null)
                        .WithMany()
                        .HasForeignKey("SchoolId", "AcademicYearId", "ClassGroupId")
                        .HasPrincipalKey("SchoolId", "AcademicYearId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edulytics.Core.Entities.Term", null)
                        .WithMany()
                        .HasForeignKey("SchoolId", "AcademicYearId", "TermId")
                        .HasPrincipalKey("SchoolId", "AcademicYearId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Edulytics.Core.Entities.AssessmentQuestion", b =>
                {
                    b.HasOne("Edulytics.Core.Entities.School", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edulytics.Core.Entities.Assessment", null)
                        .WithMany()
                        .HasForeignKey("SchoolId", "AssessmentId")
                        .HasPrincipalKey("SchoolId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Edulytics.Core.Entities.AssessmentResult", b =>
                {
                    b.HasOne("Edulytics.Data.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("EnteredByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edulytics.Core.Entities.School", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edulytics.Core.Entities.Assessment", null)
                        .WithMany()
                        .HasForeignKey("SchoolId", "AssessmentId")
                        .HasPrincipalKey("SchoolId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edulytics.Core.Entities.StudentProfile", null)
                        .WithMany()
                        .HasForeignKey("SchoolId", "StudentProfileId")
                        .HasPrincipalKey("SchoolId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Edulytics.Core.Entities.ClassAssessmentTrend", b =>
                {
                    b.HasOne("Edulytics.Core.Entities.School", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edulytics.Core.Entities.AcademicYear", null)
                        .WithMany()
                        .HasForeignKey("SchoolId", "AcademicYearId")
                        .HasPrincipalKey("SchoolId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edulytics.Core.Entities.Assessment", null)
                        .WithMany()
                        .HasForeignKey("SchoolId", "AssessmentId")
                        .HasPrincipalKey("SchoolId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edulytics.Core.Entities.Subject", null)
                        .WithMany()
                        .HasForeignKey("SchoolId", "SubjectId")
                        .HasPrincipalKey("SchoolId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edulytics.Core.Entities.ClassGroup", null)
                        .WithMany()
                        .HasForeignKey("SchoolId", "AcademicYearId", "ClassGroupId")
                        .HasPrincipalKey("SchoolId", "AcademicYearId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Edulytics.Core.Entities.ClassGroup", b =>
                {
                    b.HasOne("Edulytics.Core.Entities.School", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edulytics.Core.Entities.AcademicYear", null)
                        .WithMany()
                        .HasForeignKey("SchoolId", "AcademicYearId")
                        .HasPrincipalKey("SchoolId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edulytics.Core.Entities.GradeLevel", null)
                        .WithMany()
                        .HasForeignKey("SchoolId", "GradeLevelId")
                        .HasPrincipalKey("SchoolId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Edulytics.Core.Entities.ClassOutcomeSummary", b =>
                {
                    b.HasOne("Edulytics.Core.Entities.School", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edulytics.Core.Entities.AcademicYear", null)
                        .WithMany()
                        .HasForeignKey("SchoolId", "AcademicYearId")
                        .HasPrincipalKey("SchoolId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edulytics.Core.Entities.LearningOutcome", null)
                        .WithMany()
                        .HasForeignKey("SchoolId", "LearningOutcomeId")
                        .HasPrincipalKey("SchoolId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edulytics.Core.Entities.Subject", null)
                        .WithMany()
                        .HasForeignKey("SchoolId", "SubjectId")
                        .HasPrincipalKey("SchoolId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edulytics.Core.Entities.ClassGroup", null)
                        .WithMany()
                        .HasForeignKey("SchoolId", "AcademicYearId", "ClassGroupId")
                        .HasPrincipalKey("SchoolId", "AcademicYearId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Edulytics.Core.Entities.ClassTopicSummary", b =>
                {
                    b.HasOne("Edulytics.Core.Entities.School", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edulytics.Core.Entities.AcademicYear", null)
                        .WithMany()
                        .HasForeignKey("SchoolId", "AcademicYearId")
                        .HasPrincipalKey("SchoolId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edulytics.Core.Entities.CurriculumTopic", null)
                        .WithMany()
                        .HasForeignKey("SchoolId", "CurriculumTopicId")
                        .HasPrincipalKey("SchoolId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edulytics.Core.Entities.Subject", null)
                        .WithMany()
                        .HasForeignKey("SchoolId", "SubjectId")
                        .HasPrincipalKey("SchoolId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edulytics.Core.Entities.ClassGroup", null)
                        .WithMany()
                        .HasForeignKey("SchoolId", "AcademicYearId", "ClassGroupId")
                        .HasPrincipalKey("SchoolId", "AcademicYearId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Edulytics.Core.Entities.CurriculumFramework", b =>
                {
                    b.HasOne("Edulytics.Core.Entities.School", null)
                        .WithMany()
                        .HasForeignKey("OwnerSchoolId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Edulytics.Core.Entities.CurriculumFrameworkVersion", b =>
                {
                    b.HasOne("Edulytics.Core.Entities.CurriculumFramework", null)
                        .WithMany()
                        .HasForeignKey("FrameworkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Edulytics.Core.Entities.CurriculumTopic", b =>
                {
                    b.HasOne("Edulytics.Core.Entities.CurriculumFrameworkVersion", null)
                        .WithMany()
                        .HasForeignKey("FrameworkVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edulytics.Core.Entities.School", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edulytics.Core.Entities.GradeLevel", null)
                        .WithMany()
                        .HasForeignKey("SchoolId", "GradeLevelId")
                        .HasPrincipalKey("SchoolId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edulytics.Core.Entities.Subject", null)
                        .WithMany()
                        .HasForeignKey("SchoolId", "SubjectId")
                        .HasPrincipalKey("SchoolId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Edulytics.Core.Entities.GradeLevel", b =>
                {
                    b.HasOne("Edulytics.Core.Entities.School", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Edulytics.Core.Entities.ImportBatch", b =>
                {
                    b.HasOne("Edulytics.Data.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CompletedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Edulytics.Core.Entities.School", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edulytics.Data.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Edulytics.Core.Entities.ImportValidationError", b =>
                {
                    b.HasOne("Edulytics.Core.Entities.School", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edulytics.Core.Entities.ImportBatch", null)
                        .WithMany()
                        .HasForeignKey("SchoolId", "ImportBatchId")
                        .HasPrincipalKey("SchoolId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Edulytics.Core.Entities.LearningOutcome", b =>
                {
                    b.HasOne("Edulytics.Core.Entities.School", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edulytics.Core.Entities.CurriculumTopic", null)
                        .WithMany()
                        .HasForeignKey("SchoolId", "FrameworkVersionId", "SubjectId", "GradeLevelId", "TopicId")
                        .HasPrincipalKey("SchoolId", "FrameworkVersionId", "SubjectId", "GradeLevelId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Edulytics.Core.Entities.OutboxMessage", b =>
                {
                    b.HasOne("Edulytics.Core.Entities.School", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Edulytics.Core.Entities.QuestionLearningOutcome", b =>
                {
                    b.HasOne("Edulytics.Core.Entities.School", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edulytics.Core.Entities.AssessmentQuestion", null)
                        .WithMany()
                        .HasForeignKey("SchoolId", "AssessmentQuestionId")
                        .HasPrincipalKey("SchoolId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edulytics.Core.Entities.LearningOutcome", null)
                        .WithMany()
                        .HasForeignKey("SchoolId", "LearningOutcomeId")
                        .HasPrincipalKey("SchoolId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Edulytics.Core.Entities.SchoolAnalyticsSnapshot", b =>
                {
                    b.HasOne("Edulytics.Core.Entities.School", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edulytics.Core.Entities.AcademicYear", null)
                        .WithMany()
                        .HasForeignKey("SchoolId", "AcademicYearId")
                        .HasPrincipalKey("SchoolId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Edulytics.Core.Entities.SchoolCurriculumAdoption", b =>
                {
                    b.HasOne("Edulytics.Core.Entities.CurriculumFrameworkVersion", null)
                        .WithMany()
                        .HasForeignKey("FrameworkVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edulytics.Core.Entities.School", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edulytics.Core.Entities.AcademicYear", null)
                        .WithMany()
                        .HasForeignKey("SchoolId", "AcademicYearId")
                        .HasPrincipalKey("SchoolId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Edulytics.Core.Entities.GradeLevel", null)
                        .WithMany()
                        .HasForeignKey("SchoolId", "GradeLevelId")
                        .HasPrincipalKey("SchoolId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edulytics.Core.Entities.Subject", null)
                        .WithMany()
                        .HasForeignKey("SchoolId", "SubjectId")
                        .HasPrincipalKey("SchoolId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Edulytics.Core.Entities.StudentAnswer", b =>
                {
                    b.HasOne("Edulytics.Core.Entities.School", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edulytics.Core.Entities.AssessmentQuestion", null)
                        .WithMany()
                        .HasForeignKey("SchoolId", "AssessmentQuestionId")
                        .HasPrincipalKey("SchoolId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edulytics.Core.Entities.AssessmentResult", null)
                        .WithMany()
                        .HasForeignKey("SchoolId", "AssessmentResultId")
                        .HasPrincipalKey("SchoolId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Edulytics.Core.Entities.StudentEnrollment", b =>
                {
                    b.HasOne("Edulytics.Core.Entities.School", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edulytics.Core.Entities.AcademicYear", null)
                        .WithMany()
                        .HasForeignKey("SchoolId", "AcademicYearId")
                        .HasPrincipalKey("SchoolId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edulytics.Core.Entities.StudentProfile", null)
                        .WithMany()
                        .HasForeignKey("SchoolId", "StudentProfileId")
                        .HasPrincipalKey("SchoolId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edulytics.Core.Entities.ClassGroup", null)
                        .WithMany()
                        .HasForeignKey("SchoolId", "AcademicYearId", "ClassGroupId")
                        .HasPrincipalKey("SchoolId", "AcademicYearId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Edulytics.Core.Entities.StudentOutcomeMastery", b =>
                {
                    b.HasOne("Edulytics.Core.Entities.School", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edulytics.Core.Entities.AcademicYear", null)
                        .WithMany()
                        .HasForeignKey("SchoolId", "AcademicYearId")
                        .HasPrincipalKey("SchoolId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edulytics.Core.Entities.LearningOutcome", null)
                        .WithMany()
                        .HasForeignKey("SchoolId", "LearningOutcomeId")
                        .HasPrincipalKey("SchoolId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edulytics.Core.Entities.StudentProfile", null)
                        .WithMany()
                        .HasForeignKey("SchoolId", "StudentProfileId")
                        .HasPrincipalKey("SchoolId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edulytics.Core.Entities.Subject", null)
                        .WithMany()
                        .HasForeignKey("SchoolId", "SubjectId")
                        .HasPrincipalKey("SchoolId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edulytics.Core.Entities.ClassGroup", null)
                        .WithMany()
                        .HasForeignKey("SchoolId", "AcademicYearId", "ClassGroupId")
                        .HasPrincipalKey("SchoolId", "AcademicYearId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Edulytics.Core.Entities.StudentProfile", b =>
                {
                    b.HasOne("Edulytics.Core.Entities.School", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edulytics.Data.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Edulytics.Core.Entities.Subject", b =>
                {
                    b.HasOne("Edulytics.Core.Entities.School", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Edulytics.Core.Entities.TeacherAssignment", b =>
                {
                    b.HasOne("Edulytics.Core.Entities.School", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edulytics.Data.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("TeacherUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edulytics.Core.Entities.AcademicYear", null)
                        .WithMany()
                        .HasForeignKey("SchoolId", "AcademicYearId")
                        .HasPrincipalKey("SchoolId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edulytics.Core.Entities.Subject", null)
                        .WithMany()
                        .HasForeignKey("SchoolId", "SubjectId")
                        .HasPrincipalKey("SchoolId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edulytics.Core.Entities.ClassGroup", null)
                        .WithMany()
                        .HasForeignKey("SchoolId", "AcademicYearId", "ClassGroupId")
                        .HasPrincipalKey("SchoolId", "AcademicYearId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Edulytics.Core.Entities.Term", b =>
                {
                    b.HasOne("Edulytics.Core.Entities.School", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edulytics.Core.Entities.AcademicYear", null)
                        .WithMany()
                        .HasForeignKey("SchoolId", "AcademicYearId")
                        .HasPrincipalKey("SchoolId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Edulytics.Data.Identity.ApplicationUser", b =>
                {
                    b.HasOne("Edulytics.Core.Entities.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("School");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Edulytics.Data.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Edulytics.Data.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Edulytics.Data.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Edulytics.Data.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Edulytics.Data.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Edulytics.Data.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
